# Site settings
title: ఓ మంచి కథ.com
email: writer.suryarao@gmail.com
description: "ఓ మంచి కథ.com is a website/blog from the writer Surya Rayarao."
twitter_username: jekyllrb
github_username:  writersurya
baseurl: project-site

# Build settings
markdown: kramdown
permalink: pretty
